version: '2'

services:
  plexdrive:
    container_name: plexdrv
    image: kilhaasi/plexdrv
    restart: always
    network_mode: "bridge"
    volumes:
      - /root/.plexdrive:/config
      - /mnt:/data:shared
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    environment:
      - PUID=0
      - PGID=0
volumes:
 plexdrv-cfg:
